"""Always-on TV volume takeover over IR.

The remote's volume keys PERMANENTLY drive the TV (via the IR blaster) instead of Kodi's own volume --
independent of the disc handoff. A background service can't see key events, so a Kodi **keymap** remaps
the two volume keys globally to fast in-process ``NotifyAll`` messages; the service's ``onNotification``
catches them and fires an RCA command at the TV through the persistent IR pipe (``ir_remote``).

This module holds the keymap generation + install/remove, the notification matching, and the small
thread-safe forwarder -- no Kodi imports at module scope, so it is unit-testable off-box.
"""
from __future__ import annotations

import os
import queue
import threading

from . import ir_remote
from .kodilog import log

ADDON_ID = "service.oppokodibridge.v4"
MSG_VOLUP = "okb_volup"
MSG_VOLDOWN = "okb_voldown"
KEYMAP_FILENAME = "okb_volume_takeover.xml"

_KEYMAP_TEMPLATE = """\
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by {addon} (TV volume takeover). Installed only while the feature is on; removed when it
     is turned off. Remaps the remote's volume keys globally to NotifyAll -> the service fires IR. -->
<keymap>
  <global>
    <keyboard>
      <{key_up}>NotifyAll({addon},{msg_up})</{key_up}>
      <{key_down}>NotifyAll({addon},{msg_down})</{key_down}>
    </keyboard>
  </global>
</keymap>
"""


def keymap_xml(key_up: str = "volume_up", key_down: str = "volume_down") -> str:
    """The keymap XML that remaps the two volume keys to the takeover NotifyAll messages."""
    return _KEYMAP_TEMPLATE.format(
        addon=ADDON_ID, msg_up=MSG_VOLUP, msg_down=MSG_VOLDOWN,
        key_up=(key_up or "volume_up").strip(), key_down=(key_down or "volume_down").strip())


def install_keymap(keymaps_dir: str, key_up: str = "volume_up", key_down: str = "volume_down") -> bool:
    """Write the takeover keymap into ``keymaps_dir`` (creating it if needed). Returns True only if the
    on-disk content actually CHANGED (new file or different keys), so the caller reloads keymaps only
    when it must -- not on every settings change."""
    os.makedirs(keymaps_dir, exist_ok=True)
    path = os.path.join(keymaps_dir, KEYMAP_FILENAME)
    content = keymap_xml(key_up, key_down)
    try:
        with open(path, "r", encoding="utf-8") as fh:
            if fh.read() == content:
                return False  # already current
    except OSError:
        pass  # missing/unreadable -> (over)write below
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    return True


def remove_keymap(keymaps_dir: str) -> bool:
    """Delete the takeover keymap if present. Returns True if a file was removed (so the caller knows to
    reload keymaps). Best-effort: a missing file / unreadable dir is a no-op, never raises."""
    path = os.path.join(keymaps_dir, KEYMAP_FILENAME)
    try:
        if os.path.exists(path):
            os.remove(path)
            return True
    except OSError as exc:
        log("volume-ir: could not remove keymap {} (non-fatal): {!r}".format(path, exc))
    return False


def volume_command(method: object, config) -> object:
    """The RCA command int for a takeover NotifyAll ``method``, or ``None`` if it is not one of ours.

    Matched by the message SUFFIX so it is robust to Kodi delivering the bare message or a
    ``sender.message`` form. ``None`` for any unrelated notification (playback, library, etc.)."""
    m = str(method or "")
    if m.endswith(MSG_VOLUP):
        return int(getattr(config, "tv_code_volume_up", 16))
    if m.endswith(MSG_VOLDOWN):
        return int(getattr(config, "tv_code_volume_down", 17))
    return None


def _safe_close(blaster) -> None:
    try:
        blaster.close()
    except Exception as exc:  # noqa: BLE001 -- close must never propagate
        log("volume-ir: blaster close error (non-fatal): {!r}".format(exc))


class VolumeIrForwarder:
    """Owns a single worker thread + the persistent IR pipe. ``submit(command)`` may be called from ANY
    thread (Kodi's notification callback); the worker is the ONLY thing that touches the pipe, so there
    is no cross-thread race. The pipe is opened lazily on the first press and dropped after an idle gap
    (reopened on the next press) so an idle box doesn't hold an SSH connection open forever.

    ``update_config`` refreshes the live config (blaster host/user/key, RCA params, idle) after a settings
    change: it bumps a generation counter under a lock, and the worker rebuilds the blaster on the new
    config at the next press -- so a first-time setup (enable + fill in the host) takes effect WITHOUT a
    Kodi restart, instead of leaving the keys remapped but the pipe stuck on the old blank host."""

    def __init__(self, config, make_blaster=None, idle_seconds=None):
        self._lock = threading.Lock()
        self._config = config
        self._gen = 0
        self._make_blaster = make_blaster or ir_remote.PersistentBlaster
        self._idle_override = idle_seconds  # tests pin a short idle; production reads it from config
        self._q: "queue.Queue" = queue.Queue(maxsize=16)
        self._stop = threading.Event()
        self._worker = threading.Thread(target=self._pump, name="okb-volume-ir", daemon=True)
        self._worker.start()

    def update_config(self, config) -> None:
        """Swap in a refreshed config; the worker rebuilds the pipe on it at the next press."""
        with self._lock:
            self._config = config
            self._gen += 1

    def _snapshot(self):
        with self._lock:
            return self._config, self._gen

    def _idle_timeout(self) -> float:
        if self._idle_override is not None:
            return max(0.2, float(self._idle_override))
        cfg, _ = self._snapshot()
        return max(0.2, float(getattr(cfg, "tv_volume_ir_idle_seconds", 60.0) or 60.0))

    def submit(self, command) -> None:
        try:
            self._q.put_nowait(command)
        except queue.Full:
            log("volume-ir: queue full; dropping {} (blaster slow/unreachable)".format(command))

    def _pump(self) -> None:
        blaster = None
        blaster_gen = None
        idle_closed = True  # nothing open yet -> don't close on the first idle timeout
        try:
            while not self._stop.is_set():
                try:
                    cmd = self._q.get(timeout=self._idle_timeout())
                except queue.Empty:
                    if blaster is not None and not idle_closed:
                        _safe_close(blaster)  # idle -> drop the SSH once; reopens on the next send
                        idle_closed = True
                    continue
                if cmd is None:  # stop sentinel -> the loop condition exits below
                    continue
                cfg, gen = self._snapshot()
                if blaster is None or gen != blaster_gen:  # first use, or the config changed
                    if blaster is not None:
                        _safe_close(blaster)
                    blaster = self._make_blaster(cfg)
                    blaster_gen = gen
                blaster.send(cmd)
                idle_closed = False
        finally:
            if blaster is not None:
                _safe_close(blaster)

    def stop(self) -> None:
        self._stop.set()
        try:
            self._q.put_nowait(None)  # wake the worker off its blocking get so it exits promptly
        except queue.Full:
            pass

    def join(self, timeout=None) -> None:
        self._worker.join(timeout)
